### ISSUE TITLE
[ycabled][dualtor][active-active] `show mux status` is slow and always return `inconsistent` HWSTATUS

### ISSUE THREAD

**Issue by lolyu** [sonic-net/sonic-platform-daemons#361]
On `20220531.28` image, the `show mux status` command is slow and always return `inconsistent` for `HWSTATUS`:
```
$ time show mux s
PORT        STATUS    SERVER_STATUS    HEALTH    HWSTATUS      LAST_SWITCHOVER_TIME
----------  --------  ---------------  --------  ------------  ---------------------------
Ethernet4   active    active           healthy   inconsistent  2023-May-30 05:46:51.795124
Ethernet8   active    active           healthy   inconsistent  2023-May-30 05:46:51.734891
Ethernet12  active    active           healthy   inconsistent  2023-May-30 05:46:51.956624
Ethernet16  active    active           healthy   inconsistent  2023-May-30 05:46:51.755520
Ethernet20  active    active           healthy   inconsistent  2023-May-30 05:46:52.007026
Ethernet24  active    active           healthy   inconsistent  2023-May-30 05:46:51.826122
Ethernet28  active    active           healthy   inconsistent  2023-May-30 05:46:52.048576
Ethernet32  active    active           healthy   inconsistent  2023-May-30 05:46:51.719157
Ethernet36  active    active           healthy   inconsistent  2023-May-30 05:46:51.845886
Ethernet40  active    active           healthy   inconsistent  2023-May-30 05:46:51.981137
Ethernet44  active    active           healthy   inconsistent  2023-May-30 05:46:51.912922
Ethernet48  active    active           healthy   inconsistent  2023-May-30 05:46:51.924832
Ethernet52  active    active           healthy   inconsistent  2023-May-30 05:46:52.120600
Ethernet56  active    active           healthy   inconsistent  2023-May-30 05:46:51.992982
Ethernet60  active    active           healthy   inconsistent  2023-May-30 05:46:51.771509
Ethernet64  active    active           healthy   inconsistent  2023-May-30 05:46:51.898908
Ethernet68  active    active           healthy   inconsistent  2023-May-30 05:46:52.034526
Ethernet72  active    active           healthy   inconsistent  2023-May-30 05:46:52.061691
Ethernet76  active    active           healthy   inconsistent  2023-May-30 05:46:52.095044
Ethernet80  active    active           healthy   inconsistent  2023-May-30 05:46:52.020575
Ethernet84  active    active           healthy   inconsistent  2023-May-30 05:46:51.687364
Ethernet88  active    active           healthy   inconsistent  2023-May-30 05:46:52.132286
Ethernet92  active    active           healthy   inconsistent  2023-May-30 05:46:52.110357
Ethernet96  active    active           healthy   inconsistent  2023-May-30 05:46:51.969622

real    0m26.449s
user    0m1.366s
sys     0m0.469s
$ show mux grpc mux
Port        Direction    Presence    PeerDirection    ConnectivityState
----------  -----------  ----------  ---------------  -------------------
Ethernet4   active       True        active           READY
Ethernet8   active       True        active           READY
Ethernet12  active       True        active           READY
Ethernet16  active       True        active           READY
Ethernet20  active       True        active           READY
Ethernet24  active       True        active           READY
Ethernet28  active       True        active           READY
Ethernet32  active       True        active           READY
Ethernet36  active       True        active           READY
Ethernet40  active       True        active           READY
Ethernet44  active       True        active           READY
Ethernet48  active       True        active           READY
Ethernet52  active       True        active           READY
Ethernet56  active       True        active           READY
Ethernet60  active       True        active           READY
Ethernet64  active       True        active           READY
Ethernet68  active       True        active           READY
Ethernet72  active       True        active           READY
Ethernet76  active       True        active           READY
Ethernet80  active       True        active           READY
Ethernet84  active       True        active           READY
Ethernet88  active       True        active           READY
Ethernet92  active       True        active           READY
Ethernet96  active       True        active           READY
```

**Comment by lolyu** [comment]
From syslog, it has error message:
```
May 30 05:51:21.557188 svcstr-7050-acs-2 ERR pmon#CCmisApi: Exception occured at child thread YcableCliUpdateTask due to TypeError("handle_show_hwmode_state_cmd_arg_tbl_notification() missing 1 required positional argument: 'port'") Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 4000, in run#012    self.task_cli_worker()#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 3864, in task_cli_worker#012    handle_show_hwmode_state_cmd_arg_tbl_notification(fvp, self.cli_table_helper.port_tbl, self.cli_table_helper.xcvrd_show_hwmode_dir_cmd_sts_tbl, self.cli_table_helper.xcvrd_show_hwmode_dir_rsp_tbl, self.cli_table_helper.xcvrd_show_hwmode_dir_res_tbl, asic_index, port)#012TypeError: handle_show_hwmode_state_cmd_arg_tbl_notification() missing 1 required positional argument: 'port'
May 30 05:51:21.557464 svcstr-7050-acs-2 NOTICE pmon#CCmisApi: Setting up gRPC channel for RPC's Ethernet36 192.168.0.19
May 30 05:51:21.559970 svcstr-7050-acs-2 ERR pmon#CCmisApi: Exception occured at child thread YcableCliUpdateTask due to UnboundLocalError("local variable 'credential' referenced before assignment") Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 4120, in run#012    asyncio.run(self.task_worker())#012  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run#012    return loop.run_until_complete(main)#012  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete#012    return future.result()#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 4100, in task_worker#012    channel, stub = setup_grpc_channel_for_port(logical_port_name, soc_ipv4, asic_index, self.table_helper.get_grpc_config_tbl(), self.table_helper.get_fwd_state_response_tbl(), True)#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 568, in setup_grpc_channel_for_port#012    channel, stub = create_channel(type, level, kvp, soc_ip, port, asic_index, fwd_state_response_tbl, is_async)#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 506, in create_channel#012    channel = grpc.aio.insecure_channel("{}:{}".format(soc_ip, GRPC_PORT), credential, options=GRPC_CLIENT_OPTIONS)#012UnboundLocalError: local variable 'credential' referenced before assignment
```

**Comment by vdahiya12** [comment]
#364 fixes the issue
