### ISSUE TITLE
 Command 'sudo sfpshow eeprom' could not be executed 

### ISSUE THREAD

**Issue by yuazhe** [sonic-net/sonic-platform-daemons#439]
Error message:

```
sudo sfpshow eeprom
Traceback (most recent call last):
  File "/usr/local/bin/sfpshow", line 722, in <module>
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/sfpshow", line 646, in eeprom
    sfp.get_eeprom()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/multi_asic.py", line 157, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/sfpshow", line 552, in get_eeprom
    self.intf_eeprom[interface] = self.convert_interface_sfp_info_to_cli_output_string(
  File "/usr/local/bin/sfpshow", line 449, in convert_interface_sfp_info_to_cli_output_string
    sfp_info_output = self.convert_sfp_info_to_output_string(sfp_info_dict)
  File "/usr/local/bin/sfpshow", line 337, in convert_sfp_info_to_output_string
    output += '{}{}: {}\n'.format(indent, data_map[key], sfp_info_dict[key])
KeyError: 'active_firmware'

```
it seems after involving those two commits: 

https://github.com/sonic-net/sonic-platform-daemons/commit/7792838612e99da4001bd1265ea9c44fc8416024

https://github.com/sonic-net/sonic-platform-common/commit/796e89a8279681391ab8a125df9ed4e5eb0af126

The firmware version fields had been moved from TRANSCEIVER_INFO table to TRANSCEIVER_FIRMWARE_INFO table, but meanwhile, there is no related changes made in sfpshow script. Thereby causes the key not founding error as the script still only searches in the old TRANSCEIVER_INFO table, and there is no firmware version key exists anymore.

**Comment by prgeor** [comment]
@mihirpat1 is working on the issue
